inherit_from: .rubocop_todo.yml

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Metrics/ClassLength:
  Enabled: false

Layout/MultilineMethodCallIdentation:
  EnforcedStyle: indented
